version: "3.7"

services:
  api.notifier:
    image: senthilsweb/notifier:latest
    container_name: api.notifier
    restart: unless-stopped
    tty: true
    ports:
      - "4000:3000"
    environment:
      - API_SECRET=''