[build]
  command = "./build.sh"
  functions = "bin"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/senthilsweb/notifier"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200