name: 'notifier - GitHub Actions'

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main

env:
  project: 'notifier'
  NAME   : 'senthilsweb/notifier'

jobs:
  docker:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Get Hash
        id: hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check Hash
        run: echo "${{ env.hash }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{env.NAME}}:${{env.hash}}