name: 'notifier - GitHub Actions'

on:
  push:
    tags-ignore:
    - '**'
    branches:
    - main

env:
  project: 'notifier'
  NAME   : 'senthilsweb/notifier'
  SHA7   : ${GITHUB_SHA::7}

jobs:
  docker:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{env.NAME}}:${GITHUB_SHA::7}